version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    container_name: front
    stdin_open: true
    volumes:
       - .:/app
    env_file:
      - .env